name: "CI"
on: [push, pull_request]
jobs:
  soundness:
    name: Soundness Check
    runs-on: ubuntu-latest

    steps:
      - name: Install Mint
        run: |
          git clone https://github.com/yonaskolb/Mint.git
          cd Mint
          swift run mint install yonaskolb/mint
          echo "$HOME/.mint/bin" >> $GITHUB_PATH
          rm -rf Mint

      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Cache Mint
        uses: actions/cache@v3.3.1
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Bootstrap Mint
        run: mint bootstrap

      - name: Run soundness
        run: |
          scripts/soundness.sh
          exit $(git status --porcelain | wc -l)

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        swift: [5.8, latest]

    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift }}

      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Cache Swift PM
        uses: actions/cache@v3.3.1
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.swift }}-spm-${{ hashFiles('Package.swift') }}
          restore-keys: ${{ runner.os }}-${{ matrix.swift }}-spm-

      - name: Resolve Swift dependencies
        run: swift package resolve

      - name: Run Unit Tests
        run: swift test --parallel
